### ISSUE TITLE
Failed to load class files of expansion.

### ISSUE THREAD

**Issue by EmanYm** [TeamVK/PAPI-Enchantment#3]
I am getting this error in Purpur 1.20.6-2206 (c637b74) and PlaceholderAPI 2.11.6 [downloaded from Hangar]

https://hastebin.com/share/ihogajajen.ruby
It throws the error during every server start and every time I type "/papi reload"
Out of the expansions that I use, I narrowed it down to this [Enchantment expansion](https://wiki.placeholderapi.com/users/placeholder-list/#enchantment)

**Comment by vk2gpz** [comment]
if you're using MC 1.20.6, that class should not be involved since it is for MC 1.17-R1.

**Comment by EmanYm** [comment]
Does that mean that the expansion is not able to be used in modern versions of minecraft?

**Comment by vk2gpz** [comment]
I haven't yet updated to support 1.20.6

**Comment by EmanYm** [comment]
Understood.
I will leave it disabled for now.

On a side note, "Enchantment" expansion does not appear in the [this](https://api.extendedclip.com/all/)  expansion list, but it does on [this one](https://wiki.placeholderapi.com/users/placeholder-list/)

**Comment by vk2gpz** [comment]
> Understood. I will leave it disabled for now.
> 
> On a side note, "Enchantment" expansion does not appear in the [this](https://api.extendedclip.com/all/) expansion list, but it does on [this one](https://wiki.placeholderapi.com/users/placeholder-list/)

this is because I no longer use eCloud.  They had some security issue before and that put an extra approval process.  Hence, I now directly release the .jar file on Github.

**Comment by vk2gpz** [comment]
I've just checked the 1.3.0 and it does include code for 1.20.6.  So, your system should not be using code for 1.17.

**Comment by vk2gpz** [comment]
I'm closing this since it's been reported that it's working with 1.20.6
