### ISSUE TITLE
(Suggestion)

### ISSUE THREAD

**Issue by Khrystyian** [TeamVK/PAPI-Enchantment#4]
Adding a placeholder to calculate total enchantment that player has with Armor and Weapon, let's say, we use %enchantment_PROTECTION_ENVIRONMNETAL_total% it will display '0' or '13' or whatever the level of that enchantment the player has in total. Since the enchantment currently only allows to display them from the held item.

**Comment by vk2gpz** [comment]
try 1.3.2

**Comment by KhrysAK47** [comment]
> try 1.3.2

Thank you, I just tested it and reported a bug with it.
