### ISSUE TITLE
Error with %enchantment_<>_level_total%

### ISSUE THREAD

**Issue by Khrystyian** [TeamVK/PAPI-Enchantment#8]
The %enchantment_<>_level_total% placeholder from equipped armor only displays if player is holding any item, if player has the placeholder in the armor, it will display as 0.

How to replicate this issue:
- Enchant any armor item with any enchantment, equip it, then parse the variable when not holding any item. This does not work. (Displays as 0). Then hold any item and parse it again, it will display properly.

**Comment by vk2gpz** [comment]
try 1.4.0

**Comment by Khrystyian** [comment]
Thank you it worked!
